name: Clean System Resources and Manage Stale Issues

on:
  workflow_dispatch:

env:
  TZ: "Asia/Jakarta"

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: System cleanup
        id: cleanup
        run: |
          # Clean tools directory if exists
          [[ -n "${AGENT_TOOLSDIRECTORY}" ]] && sudo rm -rf "${AGENT_TOOLSDIRECTORY}"
          # Remove unused software directories
          sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d /usr/local/lib/android 2>/dev/null
          
          # Disable and remove swap
          sudo swapoff -a
          sudo rm -f /swapfile /mnt/swapfile
          # Update apt and purge unnecessary packages
          sudo -E apt-get -y update
          sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
          
          # Install necessary packages for OpenWrt (if needed)
          sudo -E apt-get -y install $(curl -fsSL https://tinyurl.com/ubuntu2204-make-openwrt)# Reload systemd daemon
          sudo -E systemctl daemon-reload# Clean up packages and apt cache
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          
          # Clean up user configuration files
          sudo sed -i '/NVM_DIR/d;/skel/d' /root/{.bashrc,.profile}
          sudo rm -rf ~/{.cargo,.dotnet,.rustup}
          # Set timezone
          sudo timedatectl set-timezone "${{ env.TZ }}"
          
          echo "status=success" >> ${GITHUB_OUTPUT}
          
      - name: Check cleanup status
        if: steps.cleanup.outputs.status != 'success'
        run: |
          echo "Cleanup failed!"
          exit 1
